--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/EconomyS
branches:
- master
projects:
  EconomyAPI-PM4:
    path: EconomyAPI/
    logo: EconomyAPI/icon.png
#  EconomyAirport-PM4:
#    path: EconomyAirport/
#    logo: EconomyAPI/icon.png
#  EconomyAuction-PM4-PM4:
#    path: EconomyAuction/
#    logo: EconomyAPI/icon.png
#  EconomyCasino-PM4:
#    path: EconomyCasino/
#    logo: EconomyAPI/icon.png
  EconomyJob-PM4:
    path: EconomyJob/
    logo: EconomyAPI/icon.png
  EconomyLand-PM4:
    path: EconomyLand/
    logo: EconomyAPI/icon.png
#  EconomyPShop-PM4:
#    path: EconomyPShop/
#    logo: EconomyAPI/icon.png
#  EconomyProperty-PM4:
#    path: EconomyProperty/
#    logo: EconomyAPI/icon.png
#  EconomySell-PM4:
#    path: EconomySell/
#    logo: EconomyAPI/icon.png
#  EconomyShop-PM4:
#    path: EconomyShop/
#    logo: EconomyAPI/icon.png
#  EconomyTax-PM4:
#    path: EconomyTax/
#    logo: EconomyAPI/icon.png
#  EconomyUsury-PM4:
#    path: EconomyUsury/
#    logo: EconomyAPI/icon.png
...
